INSERT INTO category (category_name) VALUES
('Electronics'),
('Clothing'),
('Books'),
('Home Appliances'),
('Sports'),
('Beauty'),
('Toys'),
('Furniture'),
('Jewelry'),
('Food'),
('Healthcare'),
('Automotive'),
('Gardening'),
('Pets'),
('Music'),
('Movies'),
('Stationery'),
('Art'),
('Games'),
('Fitness'),
('Travel'),
('Baby Products'),
('Tools'),
('Electricals'),
('Outdoor Gear'),
('Kitchenware'),
('Fashion Accessories'),
('DIY'),
('Watches'),
('Bags'),
('Camping Gear'),
('Party Supplies'),
('Computer Accessories'),
('Office Supplies'),
('Crafts'),
('Gourmet Foods'),
('Footwear'),
('Bathroom Fixtures'),
('Musical Instruments'),
('Photography'),
('Swimwear'),
('Smart Devices'),
('Cosmetics'),
('Industrial Supplies'),
('Luggage'),
('Painting Supplies'),
('Hobbies'),
('Collectibles'),
('Lighting'),
('Medical Equipment'),
('Architectural Materials'),
('Model Kits'),
('Safety Equipment'),
('Novelties'),
('Plumbing'),
('Wearable Tech'),
('Climbing Gear'),
('Instruments'),
('Cycling Gear'),
('Candles'),
('Industrial Tools'),
('Drones'),
('Virtual Reality Gear'),
('Educational Toys'),
('Sci-Fi Collectibles'),
('Comic Books'),
('Board Games'),
('Yoga Gear'),
('Pet Accessories'),
('Golf Equipment'),
('Knitting Supplies'),
('Chess Sets'),
('Cooking Utensils'),
('Riding Gear'),
('Surfing Gear'),
('Fitness Trackers'),
('Sustainable Products'),
('Antiques'),
('Skateboarding Gear'),
('Fishing Gear'),
('Handmade Crafts'),
('Skiing Gear'),
('Robotics Kits'),
('Outdoor Furniture'),
('Audio Equipment'),
('DIY Kits'),
('Sculpture Supplies'),
('Interior Decor'),
('Adventure Gear'),
('Writing Instruments'),
('Winter Wear'),
('Cycling Accessories'),
('Construction Materials'),
('Hiking Gear'),
('Board Games'),
('Puzzle Games'),
('Classic Toys');

