INSERT INTO product (product_name, description, price, category_id) VALUES
('Refrigerator', 'Large capacity, energy-efficient refrigerator', 899.99, 4),
('Washing Machine', 'Front-loading washing machine with various wash cycles', 699.99, 4),
('Microwave Oven', 'Countertop microwave oven with digital controls', 129.99, 4),
('Dishwasher', 'Built-in dishwasher with multiple wash settings', 499.99, 4),
('Air Conditioner', 'Window-mounted air conditioner, suitable for medium-sized rooms', 349.99, 4),
('Vacuum Cleaner', 'Bagless upright vacuum cleaner with HEPA filter', 179.99, 4),
('Electric Kettle', 'Stainless steel electric kettle with automatic shut-off', 39.99, 4),
('Toaster', 'Four-slice toaster with adjustable browning settings', 49.99, 4),
('Coffee Maker', 'Programmable coffee maker with 12-cup capacity', 79.99, 4),
('Blender', 'High-speed blender for smoothies and soups', 89.99, 4),
('Food Processor', 'Compact food processor with multiple attachments', 129.99, 4),
('Rice Cooker', 'Digital rice cooker with steamer basket', 59.99, 4),
('Juicer', 'Centrifugal juicer for extracting fresh fruit and vegetable juices', 69.99, 4),
('Slow Cooker', 'Programmable slow cooker with removable ceramic pot', 49.99, 4),
('Electric Grill', 'Indoor electric grill with non-stick surface', 79.99, 4),
('Air Fryer', 'Oil-less air fryer for healthier frying', 99.99, 4),
('Stand Mixer', '5-quart stand mixer with multiple attachments', 249.99, 4),
('Hand Blender', 'Immersion blender with variable speeds', 34.99, 4),
('Electric Can Opener', 'Automatic can opener with magnetic lid holder', 19.99, 4),
('Electric Toothbrush', 'Rechargeable electric toothbrush with multiple brush heads', 59.99, 4),
('Water Purifier', 'Countertop water purifier with filtration system', 129.99, 4),
('Air Purifier', 'HEPA air purifier for improving indoor air quality', 149.99, 4),
('Dehumidifier', 'Portable dehumidifier with auto-shutoff function', 179.99, 4),
('Humidifier', 'Cool mist humidifier with adjustable humidity levels', 49.99, 4),
('Electric Fan', 'Tower fan with oscillation and remote control', 69.99, 4),
('Electric Heater', 'Ceramic space heater with adjustable thermostat', 39.99, 4),
('Garbage Disposal', 'Under-sink garbage disposal unit', 149.99, 4),
('Water Heater', 'Tankless electric water heater for instant hot water', 299.99, 4),
('Electric Blanket', 'Heated electric blanket with multiple heat settings', 79.99, 4),
('Hair Dryer', 'Ionic hair dryer with diffuser and concentrator attachments', 49.99, 4),
('Electric Shaver', 'Cordless electric shaver with pivoting head', 89.99, 4),
('Steam Iron', 'Steam iron with stainless steel soleplate', 29.99, 4),
('Handheld Steamer', 'Portable handheld garment steamer', 39.99, 4),
('Cordless Vacuum', 'Bagless cordless stick vacuum cleaner', 199.99, 4),
('Air Mattress', 'Inflatable air mattress with built-in pump', 79.99, 4),
('Home Security Camera', 'Wireless home security camera with night vision', 149.99, 4),
('Robot Vacuum', 'Smart robot vacuum cleaner with mapping technology', 299.99, 4),
('Smart Thermostat', 'Wi-Fi enabled smart thermostat for energy savings', 199.99, 4),
('Electric Fireplace', 'Wall-mounted electric fireplace with realistic flames', 299.99, 4),
('Electric Pressure Cooker', 'Programmable electric pressure cooker with safety features', 129.99, 4),
('Electric Skillet', 'Non-stick electric skillet with tempered glass lid', 49.99, 4),
('Portable Air Conditioner', 'Portable air conditioner with remote control', 399.99, 4),
('Countertop Dishwasher', 'Compact countertop dishwasher for small spaces', 299.99, 4),
('Chest Freezer', 'Energy-efficient chest freezer with adjustable temperature', 299.99, 4),
('Portable Washer', 'Portable compact washer with spin cycle', 249.99, 4),
('Electric Grill Pan', 'Electric grill pan for indoor grilling', 69.99, 4),
('Electric Smoker', 'Electric smoker for smoking meats and vegetables', 199.99, 4),
('Portable Heater', 'Portable ceramic heater with adjustable thermostat', 29.99, 4),
('UV Sanitizer', 'UV sanitizer for disinfecting small items', 49.99, 4),
('Electric Air Purifier', 'Electric air purifier with ionizer and HEPA filter', 119.99, 4),
('Electric Dehumidifier', 'Mini electric dehumidifier for closets and small rooms', 59.99, 4),
('Electric Humidifier', 'Ultrasonic cool mist electric humidifier', 39.99, 4),
('Electric Fan Heater', 'Combination electric fan and heater', 49.99, 4),
('Electric Clothes Dryer', 'Portable electric clothes dryer', 149.99, 4),
('Electric Water Dispenser', 'Countertop electric water dispenser', 79.99, 4),
('Electric Food Steamer', 'Electric food steamer with multiple tiers', 59.99, 4),
('Electric Egg Cooker', 'Automatic electric egg cooker', 19.99, 4),
('Electric Bread Maker', 'Automatic bread maker with multiple settings', 89.99, 4),
('Electric Wok', 'Non-stick electric wok for stir-frying', 69.99, 4),
('Electric Pasta Maker', 'Automatic electric pasta maker', 129.99, 4),
('Electric Milk Frother', 'Automatic electric milk frother', 39.99, 4),
('Electric Ice Cream Maker', 'Automatic electric ice cream maker', 99.99, 4),
('Electric Popcorn Maker', 'Automatic electric popcorn maker', 29.99, 4),
('Electric Yogurt Maker', 'Automatic electric yogurt maker', 49.99, 4),
('Electric Griddle', 'Non-stick electric griddle for cooking pancakes and more', 39.99, 4),
('Electric Hot Plate', 'Single-burner electric hot plate', 19.99, 4),
('Electric Teapot', 'Electric teapot with automatic shut-off', 29.99, 4),
('Electric Salt and Pepper Grinder', 'Automatic electric salt and pepper grinder set', 19.99, 4),
('Electric Knife Sharpener', 'Electric knife sharpener', 39.99, 4),
('Electric Wine Opener', 'Automatic electric wine opener', 29.99, 4),
('Electric Corkscrew', 'Automatic electric corkscrew', 24.99, 4),
('Electric Can Crusher', 'Automatic electric can crusher', 49.99, 4),
('Electric Toothbrush Sterilizer', 'UV sterilizer for electric toothbrush heads', 29.99, 4),
('Electric Shoe Polisher', 'Automatic electric shoe polisher', 34.99, 4),
('Electric Window Cleaner', 'Automatic electric window cleaner', 99.99, 4),
('Electric BBQ Grill', 'Indoor electric BBQ grill', 89.99, 4),
('Electric Fondue Set', 'Electric fondue set for cheese or chocolate', 49.99, 4),
('Electric Food Warmer', 'Portable electric food warmer', 29.99, 4),
('Electric Spice Grinder', 'Electric spice and herb grinder', 19.99, 4),
('Electric Cocktail Mixer', 'Automatic electric cocktail mixer', 49.99, 4),
('Electric Milk Frothing Pitcher', 'Electric milk frothing pitcher', 39.99, 4),
('Electric Hand Warmer', 'Rechargeable electric hand warmer', 19.99, 4),
('Electric Facial Cleansing Brush', 'Electric facial cleansing brush', 49.99, 4),
('Electric Fireplace Insert', 'Electric fireplace insert for existing mantels', 199.99, 4);
INSERT INTO product (product_name, description, price, category_id) VALUES
('Basketball', 'Official size and weight basketball for outdoor play', 29.99, 5),
('Football', 'Standard size football for recreational use', 19.99, 5),
('Soccer Ball', 'Size 5 soccer ball with durable synthetic leather cover', 24.99, 5),
('Tennis Racket', 'Graphite tennis racket for intermediate players', 89.99, 5),
('Golf Clubs Set', 'Complete set of golf clubs with bag and accessories', 299.99, 5),
('Yoga Mat', 'Non-slip yoga mat for comfortable practice', 29.99, 5),
('Dumbbell Set', 'Adjustable dumbbell set with varying weights', 99.99, 5),
('Resistance Bands', 'Set of resistance bands for strength training', 19.99, 5),
('Jump Rope', 'Adjustable jump rope for cardio workouts', 9.99, 5),
('Boxing Gloves', 'High-quality boxing gloves for sparring and training', 49.99, 5),
('Punching Bag', 'Heavy-duty punching bag with hanging chains', 89.99, 5),
('Hiking Backpack', 'Water-resistant hiking backpack with multiple compartments', 79.99, 5),
('Camping Tent', '4-person camping tent with easy setup', 149.99, 5),
('Sleeping Bag', 'Lightweight sleeping bag for outdoor adventures', 39.99, 5),
('Bicycle Helmet', 'Adjustable bicycle helmet for safety while riding', 29.99, 5),
('Bike Pump', 'High-pressure bike pump with gauge', 19.99, 5),
('Running Shoes', 'Mens running shoes with cushioned sole', 79.99, 5),
('Swimming Goggles', 'Anti-fog swimming goggles with UV protection', 14.99, 5),
('Skateboard', 'Classic skateboard for tricks and cruising', 49.99, 5),
('Roller Skates', 'Adjustable roller skates for recreational skating', 39.99, 5),
('Ski Set', 'Complete ski set with skis, boots, and poles', 399.99, 5),
('Snowboard', 'Freestyle snowboard for snowboarding enthusiasts', 199.99, 5),
('Surfboard', 'Beginner-friendly surfboard for surfing lessons', 299.99, 5),
('Paddleboard', 'Inflatable paddleboard with paddle and pump', 349.99, 5),
('Kayak', 'Sit-on-top kayak for solo paddling adventures', 299.99, 5),
('Canoe', 'Sturdy canoe for two persons with paddles', 399.99, 5),
('Golf Balls', 'Pack of golf balls for practice and play', 19.99, 5),
('Tennis Balls', 'Can of tennis balls for matches and training', 4.99, 5),
('Badminton Set', 'Complete badminton set with racquets and shuttlecocks', 49.99, 5),
('Table Tennis Table', 'Foldable table tennis table for indoor/outdoor use', 299.99, 5),
('Weightlifting Gloves', 'Padded weightlifting gloves for grip and comfort', 19.99, 5),
('Gym Bag', 'Spacious gym bag with compartments for gear', 34.99, 5),
('Track Suit', 'Comfortable track suit for training and warm-ups', 49.99, 5),
('Sports Watch', 'Water-resistant sports watch with stopwatch and timer', 59.99, 5),
('Compression Socks', 'Compression socks for recovery and performance', 14.99, 5),
('Golf Glove', 'Cabretta leather golf glove for better grip', 9.99, 5),
('Hydration Pack', 'Hydration pack with water reservoir for hiking and cycling', 39.99, 5),
('Ski Goggles', 'Anti-fog ski goggles with UV protection', 49.99, 5),
('Snow Gloves', 'Waterproof snow gloves for winter sports', 24.99, 5),
('Basketball Hoop', 'Portable basketball hoop with adjustable height', 199.99, 5),
('Football Cleats', 'Molded football cleats for traction on grass', 79.99, 5),
('Soccer Goal', 'Portable soccer goal for backyard games', 99.99, 5),
('Tennis Ball Machine', 'Tennis ball machine for solo practice sessions', 499.99, 5),
('Golf Cart', 'Electric golf cart for carrying clubs on the course', 1999.99, 5),
('Yoga Blocks', 'Foam yoga blocks for support and balance', 9.99, 5),
('Weight Bench', 'Adjustable weight bench for strength training', 149.99, 5),
('Rowing Machine', 'Compact rowing machine for full-body workouts', 299.99, 5),
('Elliptical Trainer', 'Home elliptical trainer with adjustable resistance', 499.99, 5),
('Boxing Speed Bag', 'Speed bag for improving hand speed and coordination', 49.99, 5),
('Climbing Harness', 'Comfortable climbing harness for indoor and outdoor climbing', 79.99, 5),
('Trail Running Shoes', 'Trail running shoes with rugged outsole', 89.99, 5),
('Water Bottle', 'Insulated stainless steel water bottle', 19.99, 5),
('Cycling Jersey', 'Breathable cycling jersey for long rides', 49.99, 5),
('Dive Mask', 'Comfortable dive mask with tempered glass lens', 29.99, 5),
('Fishing Rod', 'Telescopic fishing rod for freshwater fishing', 39.99, 5),
('Hunting Rifle', 'Bolt-action hunting rifle with scope', 499.99, 5),
('Bow and Arrow Set', 'Recurve bow and arrow set for target shooting', 149.99, 5),
('Golf GPS Watch', 'GPS-enabled golf watch for accurate distance measurement', 249.99, 5),
('Foam Roller', 'High-density foam roller for muscle recovery', 19.99, 5),
('Outdoor Backpack', 'Waterproof outdoor backpack with roll-top closure', 69.99, 5),
('Hand Grip Strengthener', 'Adjustable hand grip strengthener for forearm workout', 9.99, 5),
('Trekking Poles', 'Collapsible trekking poles for hiking and backpacking', 39.99, 5),
('Rock Climbing Shoes', 'Technical rock climbing shoes for precise footwork', 89.99, 5),
('Snowshoes', 'Lightweight snowshoes for snow trekking', 79.99, 5),
('Mountain Bike', 'Full-suspension mountain bike for off-road trails', 999.99, 5),
('Helmet Camera', 'Action camera for capturing outdoor adventures', 149.99, 5),
('Waterproof Headlamp', 'Waterproof headlamp for hands-free lighting', 29.99, 5),
('Ski Poles', 'Aluminum ski poles with ergonomic grips', 49.99, 5),
('Knee Brace', 'Compression knee brace for support during sports', 19.99, 5),
('Snowboard Boots', 'Snowboard boots with heat-moldable liners', 199.99, 5),
('Trail Camera', 'Motion-activated trail camera for wildlife observation', 129.99, 5),
('Sport Sunglasses', 'Polarized sport sunglasses with UV protection', 39.99, 5),
('Camping Stove', 'Portable camping stove with fuel canister', 49.99, 5),
('Binoculars', 'Compact binoculars for bird watching and outdoor activities', 59.99, 5),
('Swim Fins', 'Adjustable swim fins for snorkeling and swimming', 29.99, 5),
('Diving Wetsuit', '3mm neoprene diving wetsuit for tropical waters', 149.99, 5),
('Waterproof Backpack', 'Waterproof backpack for water sports and kayaking', 89.99, 5),
('Golf Putting Green', 'Indoor putting green for practicing putting skills', 49.99, 5),
('Hand Warmer', 'Reusable hand warmer for cold weather activities', 14.99, 5),
('Tennis String', 'Durable tennis string for stringing tennis rackets', 9.99, 5),
('Pool Cue', 'Professional pool cue for billiards and pool games', 99.99, 5),
('Cycling Gloves', 'Padded cycling gloves for comfort and grip', 19.99, 5),
('Gymnastics Mat', 'Foldable gymnastics mat for tumbling and floor exercises', 79.99, 5),
('Ski Helmet', 'Lightweight ski helmet with adjustable vents', 69.99, 5),
('Snowboard Goggles', 'Snowboard goggles with anti-fog coating', 49.99, 5),
('Swimming Cap', 'Silicone swimming cap for reducing drag', 9.99, 5),
('Surfing Wetsuit', '4/3mm surfing wetsuit for cold water surfing', 199.99, 5),
('Paddleboard Paddle', 'Adjustable paddleboard paddle for paddling efficiency', 79.99, 5),
('Snorkel Set', 'Snorkel set with mask, snorkel, and fins', 59.99, 5),
('Climbing Chalk', 'Premium climbing chalk for better grip', 9.99, 5),
('Inline Skates', 'Adjustable inline skates for fitness skating', 69.99, 5),
('Fitness Tracker', 'Water-resistant fitness tracker with heart rate monitor', 79.99, 5),
('Soccer Training Cones', 'Set of soccer training cones for agility drills', 14.99, 5),
('Mountain Climbing Rope', 'Dynamic mountain climbing rope for safety and durability', 149.99, 5),
('Outdoor Knife', 'Versatile outdoor knife for camping and survival', 29.99, 5),
('Golf Putting Aid', 'Golf putting aid for improving putting accuracy', 19.99, 5),
('Winter Gloves', 'Insulated winter gloves for cold weather sports', 24.99, 5),
('Table Tennis Paddle', 'Professional table tennis paddle for competitive play', 39.99, 5),
('Archery Target', 'Foam archery target for target shooting practice', 49.99, 5),
('Baseball Bat', 'Aluminum baseball bat for recreational play', 49.99, 5),
('Softball Glove', 'Softball glove for fielding and catching', 39.99, 5),
('Rugby Ball', 'Rubber rugby ball for outdoor rugby games', 29.99, 5),
('Volleyball Net', 'Portable volleyball net for beach and backyard games', 99.99, 5),
('Handball', 'Official size handball for competitive play', 24.99, 5),
('Karate Gi', 'Traditional karate gi for martial arts training', 39.99, 5),
('Rock Climbing Harness', 'Professional rock climbing harness with gear loops', 79.99, 5),
('CrossFit Equipment Set', 'Complete set of CrossFit equipment for home gym', 399.99, 5),
('Ski Wax', 'Fluorocarbon ski wax for enhanced glide', 19.99, 5),
('Snowboarding Helmet', 'Protective snowboarding helmet with audio integration', 99.99, 5),
('Triathlon Wetsuit', 'Triathlon-specific wetsuit for open water swimming', 249.99, 5),
('Kayak Paddle', 'Lightweight kayak paddle for paddling efficiency', 79.99, 5),
('Camping Lantern', 'LED camping lantern with adjustable brightness', 24.99, 5),
('Ice Hockey Stick', 'Composite ice hockey stick for performance and durability', 149.99, 5),
('Ski Gloves', 'Waterproof ski gloves with insulated lining', 34.99, 5),
('Climbing Shoes', 'Technical climbing shoes for indoor and outdoor climbing', 89.99, 5),
('Soccer Goalkeeper Gloves', 'Professional soccer goalkeeper gloves with finger protection', 59.99, 5),
('Tennis Elbow Brace', 'Compression tennis elbow brace for support and pain relief', 14.99, 5),
('Golf Ball Retriever', 'Telescopic golf ball retriever for retrieving golf balls', 19.99, 5),
('Water Ski Rope', 'Durable water ski rope for water skiing and wakeboarding', 29.99, 5),
('Badminton Shuttlecock', 'Feather shuttlecocks for badminton play', 9.99, 5),
('Table Tennis Balls', 'Pack of table tennis balls for ping pong matches', 7.99, 5),
('Weightlifting Belt', 'Supportive weightlifting belt for heavy lifts', 29.99, 5),
('Gymnastics Rings', 'Wooden gymnastics rings for strength training', 59.99, 5),
('Ski Goggle Lens', 'Replacement lens for ski goggles', 24.99, 5),
('Fishing Tackle Box', 'Organized fishing tackle box for storing fishing gear', 39.99, 5),
('Hockey Puck', 'Official ice hockey puck for games and practice', 5.99, 5),
('Racquetball Racquet', 'Racquetball racquet for indoor racquetball games', 49.99, 5),
('Squash Racquet', 'Graphite squash racquet for competitive play', 69.99, 5),
('Swimming Pool Float', 'Inflatable swimming pool float for relaxation', 19.99, 5),
('Diving Fins', 'Flexible diving fins for underwater propulsion', 59.99, 5),
('Water Polo Ball', 'Official size water polo ball for water polo matches', 29.99, 5),
('Paddleboard Leash', 'Coiled paddleboard leash for safety in the water', 19.99, 5),
('Climbing Rope Bag', 'Durable climbing rope bag for carrying climbing ropes', 49.99, 5),
('Inline Skate Wheels', 'Replacement inline skate wheels for smooth skating', 19.99, 5),
('Fitness Headband', 'Moisture-wicking fitness headband for workouts', 9.99, 5),
('Ski Boot Bag', 'Ski boot bag with ventilated compartments', 39.99, 5),
('Snorkel Mask', 'Full-face snorkel mask for snorkeling adventures', 49.99, 5),
('Golf Tees', 'Pack of wooden golf tees for teeing off', 3.99, 5),
('Tennis Grip Tape', 'Tennis grip tape for enhancing grip on tennis racquets', 4.99, 5),
('Archery Arm Guard', 'Adjustable archery arm guard for protection', 12.99, 5),
('Baseball Glove Oil', 'Leather conditioner for baseball gloves', 7.99, 5),
('Rugby Headgear', 'Protective rugby headgear for safe play', 39.99, 5),
('Volleyball Knee Pads', 'Volleyball knee pads for protection during dives', 19.99, 5),
('Handball Gloves', 'Handball gloves for better grip and protection', 24.99, 5),
('Karate Belt', 'Colored karate belt for ranking in martial arts', 9.99, 5),
('Rock Climbing Chalk Bag', 'Chalk bag for storing climbing chalk', 19.99, 5),
('Cycling Helmet', 'Lightweight cycling helmet for road and mountain biking', 59.99, 5),
('Soccer Shin Guards', 'Adult soccer shin guards for leg protection', 19.99, 5),
('Table Tennis Net', 'Portable table tennis net for converting any table', 19.99, 5),
('Basketball Hoop Net', 'Heavy-duty basketball hoop net for outdoor courts', 9.99, 5),
('Football Mouth Guard', 'Boil-and-bite football mouth guard for custom fit', 14.99, 5),
('Ski Binding', 'Alpine ski binding for secure connection to skis', 99.99, 5),
('Climbing Carabiner', 'Lightweight climbing carabiner for quick clips', 12.99, 5),
('Surfboard Leash', 'Surfboard leash for keeping board attached in waves', 24.99, 5),
('Paddleboard Roof Rack', 'Paddleboard roof rack for transporting paddleboards', 59.99, 5),
('Snorkel Fins', 'Adjustable snorkel fins for snorkeling adventures', 39.99, 5),
('Climbing Rope Protector', 'Durable climbing rope protector for rope longevity', 29.99, 5),
('Fitness Skipping Rope', 'Adjustable fitness skipping rope for cardio workouts', 9.99, 5),
('Ski Pole Basket', 'Replacement ski pole baskets for deep snow conditions', 7.99, 5),
('Water Ski Gloves', 'Neoprene water ski gloves for grip and warmth', 29.99, 5),
('Badminton Grip Tape', 'Badminton grip tape for improving grip on racquets', 3.99, 5),
('Table Tennis Table Cover', 'Waterproof table tennis table cover for outdoor protection', 29.99, 5),
('Weightlifting Chalk', 'Magnesium weightlifting chalk for better grip', 9.99, 5),
('Gymnastics Balance Beam', 'Foldable gymnastics balance beam for home practice', 129.99, 5),
('Ski Boot Heaters', 'Battery-powered ski boot heaters for warmth', 99.99, 5),
('Snowboard Wax', 'Snowboard wax for optimal glide on snow', 14.99, 5),
('Triathlon Bike Shoes', 'Triathlon-specific bike shoes for cycling leg of races', 149.99, 5),
('Kayak Roof Rack', 'Kayak roof rack for transporting kayaks on vehicles', 79.99, 5),
('Camping Hammock', 'Lightweight camping hammock for relaxing outdoors', 49.99, 5),
('Hockey Skate Blades', 'Replacement hockey skate blades for smooth skating', 39.99, 5),
('Ski Boot Dryer', 'Electric ski boot dryer for drying wet ski boots', 49.99, 5),
('Climbing Rope Bag', 'Climbing rope bag for easy storage and transportation', 34.99, 5),
('Inline Skate Bearings', 'High-performance inline skate bearings for smooth rolling', 19.99, 5),
('Fitness Wristband', 'Fitness wristband for tracking steps and calories burned', 29.99, 5),
('Ski Waxing Iron', 'Ski waxing iron for applying wax to ski bases', 39.99, 5),
('Snowboard Stomp Pad', 'Snowboard stomp pad for added traction', 9.99, 5),
('Water Polo Cap', 'Water polo cap for identifying teams in the water', 19.99, 5),
('Paddleboard Repair Kit', 'Repair kit for fixing punctures in paddleboards', 19.99, 5),
('Climbing Finger Tape', 'Climbing finger tape for protecting and supporting fingers', 9.99, 5),
('Cycling Shoe Covers', 'Water-resistant cycling shoe covers for rainy rides', 29.99, 5),
('Soccer Referee Kit', 'Complete soccer referee kit with jersey and accessories', 49.99, 5),
('Table Tennis Robot', 'Table tennis robot for solo practice sessions', 299.99, 5),
('Basketball Pump', 'Dual-action basketball pump for inflating basketballs', 14.99, 5),
('Football Kicking Tee', 'Football kicking tee for field goals and kickoffs', 7.99, 5),
('Ski Boot Bag', 'Ski boot bag with compartments for boots and gear', 39.99, 5),
('Climbing Shoe Resoler', 'Climbing shoe resoler for restoring worn climbing shoes', 49.99, 5),
('Surf Wax', 'Surf wax for enhancing grip on surfboards', 4.99, 5),
('Paddleboard Storage Rack', 'Paddleboard storage rack for organizing paddleboards', 79.99, 5),
('Snorkeling Vest', 'Inflatable snorkeling vest for buoyancy and safety', 29.99, 5),
('Climbing Rope Pulley', 'Climbing rope pulley for efficient rope management', 49.99, 5),
('Fitness Resistance Band Set', 'Set of fitness resistance bands with varying resistance', 24.99, 5),
('Ski Pole Grips', 'Replacement ski pole grips for comfort and grip', 9.99, 5),
('Water Ski Ropes', 'Durable water ski ropes for water skiing and wakeboarding', 39.99, 5),
('Badminton Shuttlecock Tube', 'Tube of badminton shuttlecocks for extended play', 19.99, 5),
('Table Tennis Racket Case', 'Table tennis racket case for storing and protecting rackets', 14.99, 5),
('Weightlifting Wrist Wraps', 'Weightlifting wrist wraps for wrist support', 19.99, 5),
('Gymnastics Parallel Bars', 'Adjustable gymnastics parallel bars for training', 499.99, 5),
('Ski Goggle Case', 'Protective case for ski goggles and spare lenses', 19.99, 5),
('Football Penalty Flag', 'Brightly colored football penalty flag for referees', 4.99, 5),
('Soccer Captain Armband', 'Soccer captain armband for team leaders', 9.99, 5),
('Tennis Ball Hopper', 'Tennis ball hopper for easy ball collection and storage', 29.99, 5),
('Archery Bow String', 'Durable archery bow string for recurve bows', 14.99, 5),
('Baseball Batting Gloves', 'Baseball batting gloves for grip and comfort', 24.99, 5),
('Rugby Tackle Bag', 'Rugby tackle bag for practicing tackling drills', 59.99, 5),
('Volleyball Antenna', 'Volleyball antenna for marking boundaries on the net', 39.99, 5),
('Handball Goalkeeper Gloves', 'Handball goalkeeper gloves for protection and grip', 34.99, 5),
('Karate Sparring Gear Set', 'Karate sparring gear set for martial arts practice', 99.99, 5),
('Rock Climbing Rope Protector', 'Rock climbing rope protector for protecting ropes', 29.99, 5),
('CrossFit Jump Rope', 'Speed jump rope for CrossFit and fitness workouts', 12.99, 5),
('Ski Boot Backpack', 'Ski boot backpack with compartments for boots and gear', 49.99, 5),
('Snowboard Edge Tuner', 'Snowboard edge tuner for sharpening snowboard edges', 24.99, 5),
('Triathlon Bike Helmet', 'Aerodynamic triathlon bike helmet for cycling races', 149.99, 5),
('Kayak Anchor', 'Folding kayak anchor for securing kayaks in place', 29.99, 5),
('Camping Cookware Set', 'Portable camping cookware set for outdoor cooking', 59.99, 5),
('Hockey Stick Tape', 'Hockey stick tape for better grip and puck control', 7.99, 5),
('Ski Boot Dryer and Warmer', 'Electric ski boot dryer and warmer for drying and heating boots', 79.99, 5),
('Climbing Rope Protector Sleeve', 'Climbing rope protector sleeve for abrasion resistance', 19.99, 5),
('Inline Skate Helmet', 'Inline skate helmet for protection during skating', 39.99, 5),
('Fitness Exercise Dice', 'Fitness exercise dice for random workout routines', 9.88,5)
INSERT INTO product (product_name, description, price, category_id) VALUES
('Moisturizing Facial Cream', 'Hydrating facial cream for smooth and soft skin', 29.99, 6),
('Anti-Aging Serum', 'Anti-aging serum with collagen and hyaluronic acid', 49.99, 6),
('Lipstick Set', 'Set of matte and glossy lipsticks in various shades', 19.99, 6),
('Facial Cleansing Brush', 'Electric facial cleansing brush for deep cleansing', 39.99, 6),
('Hair Styling Gel', 'Strong-hold hair styling gel for all-day control', 14.99, 6),
('Eyeshadow Palette', 'Palette of shimmer and matte eyeshadows', 24.99, 6),
('Night Cream', 'Rejuvenating night cream for overnight skin repair', 34.99, 6),
('Facial Mask Set', 'Set of hydrating and purifying facial masks', 29.99, 6),
('Eyelash Curler', 'Precision eyelash curler for long-lasting curl', 9.99, 6),
('Foundation Brush', 'Professional foundation brush for seamless application', 12.99, 6),
('Perfume Gift Set', 'Fragrance gift set with perfumes and body lotions', 59.99, 6),
('Nail Polish Collection', 'Collection of trendy nail polish colors', 17.99, 6),
('Makeup Setting Spray', 'Long-lasting makeup setting spray for a flawless finish', 22.99, 6),
('Hair Dry Shampoo', 'Dry shampoo for instant hair refreshment', 16.99, 6),
('Facial Toner', 'Gentle facial toner for balancing and refreshing skin', 19.99, 6),
('Body Scrub', 'Exfoliating body scrub for smooth and radiant skin', 27.99, 6),
('Hand Cream', 'Moisturizing hand cream for soft and nourished hands', 9.99, 6),
('Beauty Blender Sponge', 'Versatile makeup blender sponge for flawless application', 8.99, 6),
('Lip Balm Trio', 'Set of nourishing lip balms in different flavors', 11.99, 6),
('Highlighter Palette', 'Palette of highlighters for luminous complexion', 21.99, 6),
('Face Primer', 'Smoothing face primer for flawless makeup application', 14.99, 6),
('Eyebrow Pencil', 'Dual-ended eyebrow pencil for defined brows', 10.99, 6),
('Body Lotion', 'Hydrating body lotion with shea butter and vitamins', 15.99, 6),
('Shaving Cream', 'Sensitive skin shaving cream for smooth shave', 13.99, 6),
('Curling Iron', 'Professional curling iron for creating curls and waves', 39.99, 6),
('Eyeliner Pen', 'Precision eyeliner pen for defined and dramatic eyes', 7.99, 6),
('Hair Conditioner', 'Nourishing hair conditioner for silky and manageable hair', 18.99, 6),
('Facial Roller', 'Jade facial roller for facial massage and relaxation', 29.99, 6),
('Body Wash Set', 'Set of refreshing and moisturizing body washes', 25.99, 6),
('Makeup Brush Cleaner', 'Deep-cleansing makeup brush cleaner solution', 9.99, 6),
('Cuticle Oil', 'Nourishing cuticle oil for healthy nails', 12.99, 6),
('Body Mist', 'Refreshing body mist with floral and fruity notes', 11.99, 6),
('Hair Serum', 'Frizz-control hair serum for smooth and shiny hair', 21.99, 6),
('Eye Cream', 'Revitalizing eye cream for reducing dark circles and puffiness', 31.99, 6),
('Blush Palette', 'Palette of blush shades for a natural flush of color', 19.99, 6),
('Facial Sunscreen', 'Broad-spectrum facial sunscreen for UV protection', 16.99, 6),
('Makeup Remover Wipes', 'Gentle makeup remover wipes for quick and easy cleansing', 8.99, 6),
('Body Butter', 'Luxurious body butter for intense hydration', 32.99, 6),
('Tinted Moisturizer', 'Lightweight tinted moisturizer for natural coverage', 26.99, 6),
('Hair Mask', 'Deep-conditioning hair mask for repairing damaged hair', 23.99, 6),
('Nail File Set', 'Set of nail files for shaping and smoothing nails', 6.99, 6),
('Facial Mist', 'Hydrating facial mist for refreshing skin throughout the day', 14.99, 6),
('Makeup Organizer', 'Acrylic makeup organizer for storing cosmetics neatly', 34.99, 6),
('Tea Tree Oil', 'Antibacterial tea tree oil for acne-prone skin', 9.99, 6),
('Dry Brush', 'Body dry brush for exfoliation and circulation stimulation', 11.99, 6),
('Hair Volumizing Powder', 'Volumizing hair powder for instant lift and texture', 13.99, 6),
('Essential Oil Diffuser', 'Aromatherapy essential oil diffuser for home relaxation', 39.99, 6),
('Hand Sanitizer Gel', 'Moisturizing hand sanitizer gel with antibacterial properties', 7.99, 6),
('Foot Cream', 'Hydrating foot cream for soft and smooth feet', 10.99, 6),
('Beauty Sleep Mask', 'Silk beauty sleep mask for comfortable sleep and skin care', 16.99, 6),
('Eyebrow Gel', 'Tinted eyebrow gel for shaping and defining eyebrows', 15.99, 6),
('Face Wash', 'Gentle foaming face wash for cleansing and refreshing skin', 12.99, 6),
('Bronzer Powder', 'Matte bronzer powder for natural sun-kissed glow', 18.99, 6),
('Hand Soap', 'Moisturizing hand soap with soothing botanical extracts', 5.99, 6),
('Facial Oil', 'Nourishing facial oil for hydration and glow', 28.99, 6),
('Hair Heat Protectant', 'Heat protectant spray for shielding hair from styling tools', 20.99, 6),
('Perfume Rollerball', 'Travel-friendly perfume rollerball for on-the-go fragrance', 26.99, 6),
('Nail Strengthener', 'Strengthening nail treatment for weak and brittle nails', 17.99, 6),
('Eyelash Growth Serum', 'Eyelash growth serum for longer and fuller lashes', 42.99, 6),
('Pore Cleansing Strips', 'Deep-cleansing pore strips for removing blackheads', 9.99, 6),
('Makeup Setting Powder', 'Translucent makeup setting powder for long-lasting wear', 15.99, 6),
('Facial Exfoliator', 'Gentle facial exfoliator for smooth and radiant skin', 13.99, 6),
('Cuticle Cream', 'Moisturizing cuticle cream for nourishing cuticles', 11.99, 6),
('Hair Detangler Spray', 'Detangling spray for easy hair combing and styling', 8.99, 6),
('Body Oil', 'Hydrating body oil with aromatic botanicals', 24.99, 6),
('Makeup Sponge Set', 'Set of latex-free makeup sponges for flawless blending', 10.99, 6),
('Foot Scrub', 'Exfoliating foot scrub for soft and smooth feet', 14.99, 6),
('Eye Gel Pads', 'Soothing eye gel pads for reducing puffiness and dark circles', 19.99, 6),
('Eyebrow Razor', 'Precision eyebrow razor for shaping and grooming brows', 6.99, 6),
('Facial Massager', 'Electric facial massager for relaxing facial massage', 34.99, 6),
('Sunless Tanner', 'Gradual sunless tanner for a natural-looking tan', 21.99, 6),
('Hydrating Sheet Mask', 'Hydrating sheet mask for instant moisture boost', 3.99, 6),
('Hair Root Touch-Up', 'Root touch-up spray for covering gray hair roots', 16.99, 6),
('Lip Scrub', 'Exfoliating lip scrub for smooth and soft lips', 7.99, 6),
('Matte Setting Spray', 'Matte finish setting spray for long-lasting makeup', 18.99, 6),
('Eyelash Extension Kit', 'DIY eyelash extension kit for voluminous lashes', 29.99, 6),
('Facial Steamers', 'Portable facial steamers for spa-like facial treatments', 49.99, 6),
('Makeup Brush Set', 'Complete set of professional makeup brushes', 39.99, 6),
('Lash Curler', 'Precision lash curler for lifting and curling lashes', 9.99, 6),
('Hair Texture Spray', 'Texturizing spray for effortless tousled hair', 14.99, 6),
('Body Wash Sponge', 'Dual-sided body wash sponge for exfoliation and cleansing', 11.99, 6),
('Facial Hair Removal', 'Facial hair removal cream for smooth skin', 12.99, 6),
('Night Serum', 'Regenerating night serum for youthful and radiant skin', 37.99, 6),
('Makeup Brush Cleaner Pad', 'Silicone makeup brush cleaning pad', 5.99, 6),
('Eyebrow Stencil Kit', 'Kit with eyebrow stencils for shaping eyebrows', 8.99, 6),
('Shower Gel Set', 'Set of refreshing shower gels in different scents', 19.99, 6),
('Hair Growth Shampoo', 'Shampoo for promoting hair growth and thickness', 24.99, 6),
('Body Spray', 'Refreshing body spray with floral and citrus notes', 9.99, 6),
('Hand Cream Set', 'Set of moisturizing hand creams in travel sizes', 15.99, 6),
('Facial Peeling Gel', 'Gentle facial peeling gel for exfoliation', 16.99, 6),
('Foot File', 'Dual-sided foot file for removing calluses and smoothing feet', 6.99, 6),
('Lip Plumper', 'Lip plumping gloss for fuller-looking lips', 11.99, 6),
('Nail Buffer', 'Buffer block for smoothing and shining nails', 3.99, 6),
('Hair Removal Wax Kit', 'At-home hair removal waxing kit', 27.99, 6),
('Tattoo Concealer', 'Concealer for covering tattoos and imperfections', 14.99, 6),
('Eyelash Primer', 'Eyelash primer for enhancing mascara wear', 10.99, 6),
('Teeth Whitening Kit', 'At-home teeth whitening kit for brighter smile', 34.99, 6),
('Facial Hair Trimmer', 'Battery-operated facial hair trimmer for grooming', 18.99, 6),
('Makeup Brush Holder', 'Decorative makeup brush holder for vanity organization', 12.99, 6),
('Foot Cream Set', 'Set of moisturizing foot creams in different scents', 19.99, 6),
('Face Mask Brush', 'Silicone face mask brush for mess-free application', 7.99, 6),
('Hair Thinning Scissors', 'Professional hair thinning scissors for precise cuts', 22.99, 6),
('Aloe Vera Gel', 'Soothing aloe vera gel for sunburn relief and skincare', 8.99, 6),
('Facial Wax Strips', 'Pre-waxed facial wax strips for easy hair removal', 9.99, 6),
('Nail Art Kit', 'Kit with tools and accessories for nail art designs', 21.99, 6),
('Hair Towel Wrap', 'Microfiber hair towel wrap for quick drying', 12.99, 6),
('Rose Water Spray', 'Refreshing rose water spray for hydrating skin', 6.99, 6),
('Under Eye Mask', 'Hydrating under eye mask for reducing puffiness and dark circles', 15.99, 6),
('Facial Hair Growth Serum', 'Serum for promoting facial hair growth', 25.99, 6)
INSERT INTO product (product_name, description, price, category_id) VALUES
('Remote Control Car', 'High-speed remote control car for racing enthusiasts', 49.99, 7),
('Board Game Set', 'Set of classic board games for family game nights', 39.99, 7),
('LEGO Star Wars Set', 'LEGO Star Wars Millennium Falcon construction set', 79.99, 7),
('Dollhouse with Furniture', 'Wooden dollhouse with mini furniture accessories', 69.99, 7),
('Toy Kitchen Playset', 'Interactive toy kitchen playset with cooking accessories', 59.99, 7),
('Teddy Bear Plush', 'Soft and cuddly teddy bear plush toy', 19.99, 7),
('Hot Wheels Track Set', 'Hot Wheels track set with loops and curves', 29.99, 7),
('Barbie Dreamhouse', 'Barbie Dreamhouse with multiple rooms and accessories', 89.99, 7),
('RC Quadcopter Drone', 'Remote control quadcopter drone with HD camera', 99.99, 7),
('Nerf Blaster Set', 'Nerf blaster set with darts and targets', 34.99, 7),
('Action Figure Playset', 'Action figure playset with multiple characters', 24.99, 7),
('Puzzle Mat', 'Educational puzzle mat with numbers and letters', 19.99, 7),
('Toy Train Set', 'Classic toy train set with tracks and locomotive', 44.99, 7),
('Art Supplies Kit', 'Art supplies kit with paints, brushes, and canvas', 29.99, 7),
('Remote Control Helicopter', 'Mini remote control helicopter for indoor flights', 39.99, 7),
('Play-Doh Set', 'Play-Doh set with molds and multiple colors', 14.99, 7),
('Building Blocks Set', 'Large set of building blocks for creative construction', 49.99, 7),
('Dinosaur Figures Pack', 'Pack of realistic dinosaur figures for imaginative play', 22.99, 7),
('Toy Cash Register', 'Electronic toy cash register with play money', 24.99, 7),
('Water Balloon Launcher', 'Outdoor water balloon launcher for summer fun', 17.99, 7),
('Barbie Doll Set', 'Barbie doll set with fashion accessories', 19.99, 7),
('Remote Control Boat', 'Speedy remote control boat for pool and lake races', 54.99, 7),
('Magic Kit', 'Magic kit with tricks and illusions for budding magicians', 27.99, 7),
('Baby Doll Playset', 'Baby doll playset with crib, stroller, and accessories', 32.99, 7),
('Art Easel for Kids', 'Adjustable art easel for painting and drawing', 34.99, 7),
('Toy Microscope Kit', 'Educational toy microscope kit with slides', 29.99, 7),
('Dress-Up Costume Set', 'Set of dress-up costumes for imaginative play', 39.99, 7),
('Marble Run Set', 'Colorful marble run set with tracks and marbles', 26.99, 7),
('Toy Drum Set', 'Toy drum set with drumsticks and cymbals', 49.99, 7),
('RC Monster Truck', 'Remote control monster truck with off-road capabilities', 69.99, 7),
('Baby Activity Gym', 'Interactive baby activity gym with hanging toys', 59.99, 7),
('LEGO City Police Station', 'LEGO City police station building set', 79.99, 7),
('Stuffed Animal Zoo', 'Stuffed animal storage zoo with mesh sides', 19.99, 7),
('Toy Tool Set', 'Toy tool set with plastic tools for pretend play', 14.99, 7),
('Doll Stroller', 'Doll stroller with adjustable handle and storage basket', 24.99, 7),
('Kite Kit', 'DIY kite kit with materials for building and decorating', 11.99, 7),
('RC Airplane', 'Remote control airplane for outdoor flying adventures', 59.99, 7),
('Interactive Learning Toy', 'Interactive learning toy with games and activities', 39.99, 7),
('Finger Puppet Set', 'Set of colorful finger puppets for storytelling', 9.99, 7),
('Toy Telescope', 'Toy telescope with adjustable focus for observing', 29.99, 7),
('Toy Cash Register with Scanner', 'Toy cash register with scanner and play money', 29.99, 7),
('Foam Dart Blaster', 'Foam dart blaster gun for target shooting', 19.99, 7),
('Glow-in-the-Dark Stars Kit', 'Glow-in-the-dark stars kit for decorating ceilings', 12.99, 7),
('Musical Instrument Set', 'Set of musical instruments for kids including xylophone', 49.99, 7),
('RC Racing Boat', 'Remote control racing boat for high-speed water races', 74.99, 7),
('Construction Vehicle Toy Set', 'Set of construction vehicle toys with moving parts', 32.99, 7),
('Toy Binoculars', 'Toy binoculars for outdoor exploration and bird watching', 15.99, 7),
('Kids Gardening Set', 'Kids gardening set with tools and watering can', 21.99, 7),
('Wooden Train Set', 'Classic wooden train set with tracks and train cars', 34.99, 7),
('Bubble Machine', 'Automatic bubble machine for endless bubble fun', 19.99, 7),
('Doctor Playset', 'Pretend play doctor playset with medical accessories', 26.99, 7),
('Sandbox Digger Toy', 'Sandbox digger toy for digging and scooping sand', 39.99, 7),
('Toy Pirate Ship', 'Toy pirate ship with sails and pirate figurines', 29.99, 7),
('Toy Binoculars for Kids', 'Adjustable toy binoculars for kids for outdoor adventures', 12.99, 7),
('Art Desk for Kids', 'Kids art desk with storage and adjustable tilt', 49.99, 7),
('Inflatable Bounce House', 'Inflatable bounce house for backyard fun', 179.99, 7),
('Remote Control Robot', 'Remote control robot toy with walking and dancing', 49.99, 7),
('Kids Bowling Set', 'Kid bowling set with mini bowling pins and balls', 16.99, 7),
('Toy Cash Register with Play Money', 'Toy cash register with play money and scanner', 22.99, 7),
('Toy Microscope for Kids', 'Toy microscope for kids with prepared slides', 18.99, 7),
('Toy Dump Truck', 'Toy dump truck with movable parts for loading', 27.99, 7),
('Toddler Climbing Toy', 'Toddler climbing toy with slide and climbing wall', 69.99, 7),
('Toy Telescope for Kids', 'Toy telescope for kids with adjustable focus', 19.99, 7),
('Kid Tent', 'Kid tent for indoor and outdoor play', 34.99, 7),
('Building Blocks for Toddlers', 'Building blocks set for toddlers with large pieces', 21.99, 7),
('Remote Control Tank', 'Remote control tank with turret and tracks', 59.99, 7),
('Art Smock for Kids', 'Waterproof art smock for kids for messy art projects', 8.99, 7),
('Toy Doctor Kit', 'Toy doctor kit with stethoscope and medical tools', 14.99, 7),
('Kid Puzzle Set', 'Set of educational puzzles for kids', 11.99, 7),
('Toy Fire Truck', 'Toy fire truck with lights, sounds, and extending ladder', 39.99, 7),
('Toy Camera for Kids', 'Toy camera for kids with photo effects and frames', 16.99, 7),
('Kid Tool Bench', 'Kid tool bench with tools and storage', 42.99, 7),
('Doll Clothes Set', 'Set of clothes and accessories for dolls', 9.99, 7),
('RC Rock Crawler', 'Remote control rock crawler with off-road capabilities', 79.99, 7),
('Kid Kitchen Playset', 'Kid kitchen playset with sink, stove, and accessories', 64.99, 7),
('Kid Easel', 'Kid easel with chalkboard and whiteboard sides', 29.99, 7),
('Toy Cash Register with Scanner and Credit Card', 'Toy cash register with scanner, credit card, and play money', 34.99, 7),
('Toy Bowling Set', 'Toy bowling set with mini bowling pins and ball', 12.99, 7),
('Kid Workbench', 'Kid workbench with tools and building accessories', 37.99, 7),
('Educational Flashcards Set', 'Set of educational flashcards for learning', 6.99, 7)
INSERT INTO product (product_name, description, price, category_id) VALUES
('Modern Coffee Table', 'Sleek and modern coffee table with tempered glass top', 199.99, 8),
('Sectional Sofa', 'L-shaped sectional sofa with plush cushions', 799.99, 8),
('Dining Table Set', 'Wooden dining table set with chairs for four', 499.99, 8),
('Accent Chair', 'Upholstered accent chair with tufted back', 299.99, 8),
('Queen Bed Frame', 'Queen-size bed frame with upholstered headboard', 599.99, 8),
('TV Stand', 'Contemporary TV stand with storage compartments', 249.99, 8),
('Bar Stools Set', 'Set of adjustable bar stools with swivel seats', 149.99, 8),
('Office Desk', 'Modern office desk with storage drawers', 349.99, 8),
('Bookshelf', 'Tall wooden bookshelf with adjustable shelves', 179.99, 8),
('Folding Table', 'Foldable table with durable metal frame', 89.99, 8),
('Nightstand', 'Bedside nightstand with drawer and shelf', 129.99, 8),
('Console Table', 'Narrow console table with sleek design', 159.99, 8),
('Lounge Chair', 'Comfortable lounge chair with fabric upholstery', 279.99, 8),
('Dresser with Mirror', 'Wooden dresser with attached mirror', 449.99, 8),
('Platform Bed', 'Modern platform bed with low-profile design', 399.99, 8),
('Computer Desk', 'Compact computer desk with keyboard tray', 119.99, 8),
('Rocking Chair', 'Classic rocking chair with solid wood construction', 199.99, 8),
('Cabinet Storage Unit', 'Tall cabinet storage unit with doors', 219.99, 8),
('Bunk Bed', 'Wooden bunk bed with built-in ladder', 599.99, 8),
('Entryway Bench', 'Upholstered entryway bench with shoe storage', 149.99, 8),
('Couch Set', 'Set of matching couches with fabric upholstery', 899.99, 8),
('Bar Table', 'High bar table with metal frame and wood top', 179.99, 8),
('Outdoor Patio Set', 'Outdoor patio furniture set with table and chairs', 679.99, 8),
('Armchair', 'Stylish armchair with upholstered seat and back', 249.99, 8),
('Folding Chairs Set', 'Set of folding chairs with padded seats', 99.99, 8),
('Gaming Desk', 'Gaming desk with LED lights and cable management', 299.99, 8),
('Vanity Set', 'Makeup vanity set with mirror and stool', 189.99, 8),
('Kids Table and Chairs Set', 'Kids table and chairs set for play and activities', 129.99, 8),
('Buffet Cabinet', 'Wooden buffet cabinet with storage drawers', 329.99, 8),
('Outdoor Lounge Set', 'Outdoor lounge furniture set with sofa and coffee table', 749.99, 8),
('Bistro Table Set', 'Bistro table set with two chairs for small spaces', 149.99, 8),
('Counter Height Stools', 'Counter height stools with padded seats', 129.99, 8),
('Writing Desk', 'Compact writing desk with open shelves', 99.99, 8),
('Shoe Rack Bench', 'Shoe rack bench with cushioned seat', 79.99, 8),
('Bar Cart', 'Metal bar cart with wheels for serving drinks', 89.99, 8),
('Accent Cabinet', 'Accent cabinet with decorative fretwork', 179.99, 8),
('Bedside Table', 'Bedside table with drawer and open shelf', 79.99, 8),
('Lift-Top Coffee Table', 'Coffee table with lift-top for storage', 219.99, 8),
('Glider Recliner', 'Glider recliner chair with plush padding', 349.99, 8),
('Desk Chair', 'Adjustable desk chair with ergonomic design', 149.99, 8),
('Platform Storage Bed', 'Platform bed with built-in storage drawers', 449.99, 8),
('Console Cabinet', 'Console cabinet with glass doors and shelves', 199.99, 8),
('Kid Bookshelf', 'Kid bookshelf with colorful bins for storage', 119.99, 8),
('Futon Sofa Bed', 'Futon sofa bed with linen upholstery', 299.99, 8),
('Kitchen Cart', 'Rolling kitchen cart with butcher block top', 129.99, 8),
('Foldable Chairs Set', 'Set of foldable chairs for outdoor use', 69.99, 8),
('Storage Ottoman', 'Rectangular storage ottoman with padded top', 79.99, 8),
('Corner Desk', 'L-shaped corner desk with space-saving design', 229.99, 8),
('Storage Bench', 'Upholstered storage bench with lift-top', 149.99, 8),
('Bar Stools with Back', 'Bar stools with backrest and swivel seats', 169.99, 8),
('Computer Chair', 'Mesh back computer chair with adjustable arms', 119.99, 8),
('Outdoor Dining Set', 'Outdoor dining set with table and chairs', 549.99, 8),
('Leather Recliner', 'Leather recliner chair with manual reclining mechanism', 399.99, 8),
('Nesting Tables', 'Set of nesting tables with wood and metal accents', 99.99, 8),
('Kid Desk and Chair Set', 'Kid desk and chair set with adjustable height', 109.99, 8),
('Storage Cabinet', 'Tall storage cabinet with multiple shelves', 249.99, 8),
('Sofa Table', 'Narrow sofa table with drawer and shelf', 119.99, 8),
('Adjustable Bed Frame', 'Adjustable bed frame with remote control', 799.99, 8),
('End Tables Set', 'Set of two end tables with wood grain finish', 139.99, 8),
('Counter Height Dining Table', 'Counter height dining table with storage base', 379.99, 8),
('Cocktail Ottoman', 'Round cocktail ottoman with tufted upholstery', 179.99, 8),
('Rolling Storage Cart', 'Metal rolling storage cart with shelves', 59.99, 8),
('Pub Table Set', 'Pub table set with stools for casual dining', 229.99, 8),
('Round Dining Table', 'Round dining table with pedestal base', 249.99, 8),
('Vanity Desk', 'Vanity desk with mirror and storage drawers', 219.99, 8),
('Bookcase with Doors', 'Bookcase with glass doors and adjustable shelves', 289.99, 8),
('Counter Stools Set', 'Set of counter stools with backrests', 189.99, 8),
('Convertible Sofa Bed', 'Convertible sofa bed with linen upholstery', 349.99, 8),
('Foldable Storage Bench', 'Foldable storage bench with removable lid', 69.99, 8),
('Metal Bed Frame', 'Metal bed frame with headboard and footboard', 129.99, 8),
('Farmhouse Coffee Table', 'Farmhouse style coffee table with distressed finish', 179.99, 8),
('Gaming Chair', 'Gaming chair with racing style design', 249.99, 8),
('Mirrored Nightstand', 'Mirrored nightstand with drawer and crystal knob', 159.99, 8),
('Storage Trunk', 'Wooden storage trunk with hinged lid', 109.99, 8),
('Rolling Desk Chair', 'Rolling desk chair with padded seat and back', 99.99, 8),
('Round Ottoman', 'Round ottoman with storage and fabric upholstery', 89.99, 8),
('Corner TV Stand', 'Corner TV stand with open shelves and cabinets', 199.99, 8),
('Buffet Server', 'Buffet server with drawers and wine storage', 299.99, 8),
('Folding Tray Table Set', 'Set of folding tray tables with stand', 49.99, 8),
('Upholstered Bench', 'Upholstered bench with button-tufted seat', 129.99, 8),
('Metal Bar Stools', 'Metal bar stools with backrest and footrest', 79.99, 8),
('Industrial Dining Table', 'Industrial style dining table with metal legs', 279.99, 8),
('Wooden Bench', 'Wooden bench with slatted seat', 109.99, 8),
('Sleeper Sofa', 'Sleeper sofa with memory foam mattress', 699.99, 8),
('Mid-Century Modern Chair', 'Mid-century modern chair with molded seat', 149.99, 8)
INSERT INTO product (product_name, description, price, category_id) VALUES
('Diamond Stud Earrings', 'Classic diamond stud earrings in white gold setting', 599.99, 9),
('Gold Chain Necklace', '14k gold chain necklace with lobster clasp', 399.99, 9),
('Sapphire Ring', 'Genuine sapphire ring with diamond accents', 799.99, 9),
('Pearl Bracelet', 'Cultured pearl bracelet with sterling silver clasp', 299.99, 9),
('Emerald Pendant', 'Emerald pendant necklace in 18k yellow gold', 499.99, 9),
('Ruby Eternity Band', 'Ruby eternity band ring in platinum', 899.99, 9),
('Opal Drop Earrings', 'Opal drop earrings with leverback closures', 349.99, 9),
('Amethyst Necklace', 'Amethyst necklace with sterling silver chain', 199.99, 9),
('Tanzanite Stud Earrings', 'Tanzanite stud earrings in white gold', 449.99, 9),
('Topaz Bracelet', 'Blue topaz bracelet with adjustable clasp', 279.99, 9),
('Garnet Ring', 'Garnet ring with floral design in rose gold', 349.99, 9),
('Peridot Pendant', 'Peridot pendant necklace with diamond accents', 229.99, 9),
('Citrine Earrings', 'Citrine earrings with 14k gold posts', 179.99, 9),
('Aquamarine Bracelet', 'Aquamarine bracelet with toggle clasp', 319.99, 9),
('Turquoise Ring', 'Turquoise ring with sterling silver setting', 159.99, 9),
('Moonstone Pendant', 'Moonstone pendant necklace in yellow gold', 249.99, 9),
('Onyx Cufflinks', 'Black onyx cufflinks with silver-tone settings', 129.99, 9),
('Hoop Earrings Set', 'Set of three hoop earrings in different sizes', 89.99, 9),
('Charm Bracelet', 'Charm bracelet with various themed charms', 149.99, 9),
('Silver Chain Anklet', 'Sterling silver chain anklet with lobster clasp', 69.99, 9),
('Rose Quartz Ring', 'Rose quartz ring with simple band', 109.99, 9),
('Gold Hoop Earrings', 'Classic gold hoop earrings with latch closures', 119.99, 9),
('Enamel Pin Set', 'Set of enamel pins in assorted designs', 49.99, 9),
('Personalized Name Necklace', 'Customized name necklace in sterling silver', 79.99, 9),
('Cameo Brooch', 'Vintage cameo brooch with ornate frame', 129.99, 9),
('Jade Bangle', 'Green jade bangle bracelet with hinge closure', 199.99, 9),
('Cluster Diamond Ring', 'Cluster diamond ring with white gold band', 499.99, 9),
('Stackable Gemstone Rings Set', 'Set of stackable gemstone rings in silver', 169.99, 9),
('Pendant Necklace with Initial', 'Initial pendant necklace with cable chain', 59.99, 9),
('Pearl Drop Earrings', 'Pearl drop earrings with 14k gold hooks', 139.99, 9),
('Vintage Locket', 'Antique-style locket necklace with floral engraving', 189.99, 9),
('Crystal Stud Earrings', 'Crystal stud earrings with stainless steel posts', 39.99, 9),
('Gold Plated Cuff Bracelet', 'Gold plated cuff bracelet with hammered texture', 109.99, 9),
('Cross Pendant', 'Sterling silver cross pendant with chain', 79.99, 9),
('Heart-Shaped Charm', 'Heart-shaped charm with cubic zirconia accents', 49.99, 9),
('Gemstone Tennis Bracelet', 'Gemstone tennis bracelet with secure clasp', 249.99, 9),
('Infinity Symbol Ring', 'Infinity symbol ring in sterling silver', 89.99, 9),
('Diamond Halo Necklace', 'Diamond halo necklace in white gold setting', 359.99, 9),
('Initial Stud Earrings', 'Initial stud earrings with cubic zirconia stones', 69.99, 9),
('Turquoise Drop Pendant', 'Turquoise drop pendant necklace with silver chain', 129.99, 9),
('Gold Filigree Ring', 'Gold filigree ring with intricate design', 179.99, 9),
('Dangle Charm Bracelet', 'Dangle charm bracelet with lobster clasp', 99.99, 9),
('Cluster Gemstone Earrings', 'Cluster gemstone earrings with leverback closures', 109.99, 9),
('Personalized Birthstone Ring', 'Personalized birthstone ring with engraved names', 199.99, 9),
('Cubic Zirconia Solitaire Necklace', 'Cubic zirconia solitaire necklace with chain', 59.99, 9),
('Stackable Band Rings Set', 'Set of stackable band rings in assorted designs', 79.99, 9),
('Gold Chain Bracelet', 'Gold chain bracelet with lobster clasp', 129.99, 9),
('Crystal Pendant Necklace', 'Crystal pendant necklace with silver chain', 49.99, 9),
('Hematite Bead Bracelet', 'Hematite bead bracelet with stretchable band', 39.99, 9),
('Opal Ring', 'Opal ring with sterling silver band', 149.99, 9),
('Starburst Stud Earrings', 'Starburst stud earrings with crystal accents', 29.99, 9),
('Anklet with Charms', 'Anklet with assorted charms and adjustable chain', 19.99, 9),
('Gold Drop Earrings', 'Gold drop earrings with hook closures', 89.99, 9),
('Moon and Star Necklace', 'Moon and star necklace with adjustable chain', 69.99, 9),
('Amber Pendant', 'Amber pendant with sterling silver setting', 109.99, 9),
('Rhinestone Choker Necklace', 'Rhinestone choker necklace with lobster clasp', 29.99, 9),
('Sterling Silver Toe Ring', 'Sterling silver toe ring with adjustable fit', 9.99, 9),
('Diamond Wedding Band', 'Diamond wedding band in white gold', 499.99, 9),
('Labradorite Necklace', 'Labradorite necklace with chain in silver', 89.99, 9),
('Gold Bar Necklace', 'Gold bar necklace with adjustable chain', 59.99, 9),
('Crystal Hoop Earrings', 'Crystal hoop earrings with latch back closures', 39.99, 9),
('Charm Bracelet with Heart Charms', 'Charm bracelet with heart-shaped charms', 79.99, 9),
('Ruby Drop Earrings', 'Ruby drop earrings with sterling silver hooks', 129.99, 9),
('Emerald Ring', 'Emerald ring with diamond accents in yellow gold', 279.99, 9),
('Silver Anklet', 'Sterling silver anklet with adjustable chain', 19.99, 9),
('Initial Pendant Necklace', 'Initial pendant necklace with cable chain', 49.99, 9),
('Turquoise Bracelet', 'Turquoise bracelet with silver toggle clasp', 59.99, 9),
('Gold Stud Earrings', 'Gold stud earrings with butterfly backings', 69.99, 9),
('Cluster Pearl Necklace', 'Cluster pearl necklace with sterling silver chain', 149.99, 9),
('Hoop Earrings with Crystals', 'Hoop earrings with crystal accents', 29.99, 9),
('Silver Heart Locket', 'Silver heart locket with engraved floral design', 99.99, 9),
('Gemstone Cluster Ring', 'Gemstone cluster ring with sterling silver band', 199.99, 9),
('Diamond Cross Pendant', 'Diamond cross pendant with chain in white gold', 299.99, 9),
('Personalized Name Bracelet', 'Personalized name bracelet with adjustable fit', 39.99, 9),
('Cameo Necklace', 'Vintage cameo necklace with detailed carving', 79.99, 9),
('Gold Bangle Bracelet', 'Gold bangle bracelet with hinge closure', 119.99, 9),
('Pearl Drop Pendant', 'Pearl drop pendant with sterling silver chain', 69.99, 9),
('Lapis Lazuli Ring', 'Lapis lazuli ring with intricate sterling silver band', 89.99, 9),
('Gemstone Chandelier Earrings', 'Gemstone chandelier earrings with sterling silver hooks', 179.99, 9),
('Anklet with Beads', 'Anklet with colorful beads and adjustable chain', 24.99, 9),
('Diamond Nose Stud', 'Diamond nose stud with screw-back design', 49.99, 9)
INSERT INTO product (product_name, description, price, category_id) VALUES
('Organic Quinoa', 'Certified organic quinoa from high-altitude farms', 9.99, 10),
('Extra Virgin Olive Oil', 'Cold-pressed extra virgin olive oil from Italy', 14.99, 10),
('Pure Raw Honey', 'Unfiltered pure raw honey from local beekeepers', 12.99, 10),
('Whole Grain Pasta', 'Whole grain pasta made with durum wheat', 3.99, 10),
('Organic Chia Seeds', 'Organic chia seeds packed with omega-3 fatty acids', 7.99, 10),
('Artisanal Dark Chocolate', 'Artisanal dark chocolate with 70% cocoa content', 5.99, 10),
('Japanese Green Tea', 'Premium Japanese green tea leaves', 8.99, 10),
('Organic Coconut Oil', 'Cold-pressed organic coconut oil', 11.99, 10),
('Gluten-Free Oats', 'Certified gluten-free rolled oats', 6.99, 10),
('Gourmet Coffee Beans', 'Single-origin gourmet coffee beans', 15.99, 10),
('Organic Almonds', 'Raw organic almonds from sustainable farms', 10.99, 10),
('Wildflower Blossom Honey', 'Wildflower blossom honey with rich floral notes', 13.99, 10),
('Organic Flaxseed', 'Organic whole flaxseed packed with fiber and omega-3', 4.99, 10),
('Imported Parmesan Cheese', 'Imported Parmesan cheese aged for 24 months', 7.49, 10),
('Himalayan Pink Salt', 'Himalayan pink salt mined from ancient sea beds', 3.49, 10),
('Organic Maple Syrup', 'Pure organic maple syrup from Vermont', 16.99, 10),
('Wild-Caught Salmon Fillets', 'Wild-caught Alaskan salmon fillets', 19.99, 10),
('Artisan Bread Loaf', 'Freshly baked artisan bread loaf', 4.99, 10),
('Natural Peanut Butter', 'Creamy natural peanut butter without added sugars', 5.99, 10),
('Organic Brown Rice', 'Organic long-grain brown rice', 8.49, 10),
('Greek Yogurt', 'Creamy Greek yogurt with live cultures', 3.99, 10),
('Raw Cashew Nuts', 'Raw cashew nuts packed with protein and healthy fats', 9.99, 10),
('Quinoa Pasta', 'Gluten-free quinoa pasta made from organic quinoa', 6.99, 10),
('Cold-Pressed Juice', 'Cold-pressed juice made from organic fruits and vegetables', 7.99, 10),
('Organic Dried Cranberries', 'Organic dried cranberries sweetened with apple juice', 5.49, 10),
('Sun-Dried Tomatoes', 'Sun-dried tomatoes packed in olive oil', 6.49, 10),
('Organic Matcha Powder', 'Premium organic matcha powder from Japan', 18.99, 10),
('Raw Honeycomb', 'Raw honeycomb harvested from local apiaries', 14.49, 10),
('Whole Wheat Flour', 'Organic whole wheat flour for baking', 4.99, 10),
('Aged Balsamic Vinegar', 'Aged balsamic vinegar from Modena, Italy', 10.99, 10),
('Organic Spirulina Powder', 'Organic spirulina powder rich in nutrients', 12.99, 10),
('Whole Grain Cereal', 'Whole grain cereal with dried fruits and nuts', 5.99, 10),
('Gourmet Truffle Oil', 'Gourmet truffle oil infused with real truffle essence', 19.99, 10),
('Organic Red Lentils', 'Organic red lentils rich in protein and fiber', 3.99, 10),
('Premium Extra Virgin Coconut Oil', 'Premium extra virgin coconut oil for cooking and baking', 9.99, 10),
('Italian Arborio Rice', 'Italian Arborio rice for creamy risotto dishes', 7.99, 10),
('Organic Cacao Nibs', 'Organic cacao nibs for snacking and baking', 8.49, 10),
('Organic Goji Berries', 'Organic goji berries packed with antioxidants', 11.49, 10),
('Artisanal Pasta Sauce', 'Artisanal pasta sauce made with vine-ripened tomatoes', 6.49, 10),
('Organic Spelt Flour', 'Organic spelt flour for baking bread and pastries', 5.49, 10),
('Grass-Fed Whey Protein Powder', 'Grass-fed whey protein powder for muscle recovery', 24.99, 10),
('Organic Raw Cacao Powder', 'Organic raw cacao powder for baking and smoothies', 13.99, 10),
('Organic Pumpkin Seeds', 'Organic pumpkin seeds rich in magnesium and zinc', 6.99, 10),
('Gourmet Sea Salt', 'Gourmet sea salt flakes from the Mediterranean', 9.49, 10),
('Organic Dried Mango', 'Organic dried mango slices with no added sugars', 7.99, 10),
('Almond Flour', 'Blanched almond flour for gluten-free baking', 11.49, 10),
('Organic White Quinoa', 'Organic white quinoa for salads and pilafs', 10.49, 10),
('Chia Seed Pudding Mix', 'Chia seed pudding mix with coconut milk powder', 5.99, 10),
('Organic Black Beans', 'Organic black beans rich in fiber and protein', 4.49, 10),
('Organic Raisins', 'Organic raisins with no sulfites added', 5.99, 10),
('Sprouted Whole Grain Bread', 'Sprouted whole grain bread with seeds and nuts', 6.99, 10)
INSERT INTO product (product_name, description, price, category_id) VALUES
('Smartphone', 'High-performance smartphone with advanced features', 699.99, 1),
('Laptop', 'Thin and light laptop with fast processing power', 1299.99, 1),
('Smart TV', '4K Ultra HD smart TV with built-in streaming apps', 899.99, 1),
('Tablet', 'Versatile tablet for work and entertainment', 499.99, 1),
('Wireless Headphones', 'Noise-cancelling wireless headphones with long battery life', 349.99, 1),
('Gaming Console', 'Next-generation gaming console with immersive graphics', 499.99, 1),
('Bluetooth Speaker', 'Portable Bluetooth speaker with rich sound quality', 99.99, 1),
('Digital Camera', 'High-resolution digital camera with zoom lens', 599.99, 1),
('Smart Watch', 'Fitness tracker and smart watch with heart rate monitor', 299.99, 1),
('Home Security Camera', 'Wireless home security camera with night vision', 199.99, 1),
('Desktop Computer', 'Powerful desktop computer for home or office use', 1499.99, 1),
('External Hard Drive', 'Portable external hard drive for backup and storage', 129.99, 1),
('Wireless Router', 'Dual-band wireless router for high-speed internet', 79.99, 1),
('VR Headset', 'Virtual reality headset for immersive gaming and experiences', 399.99, 1),
('Wireless Mouse', 'Ergonomic wireless mouse for smooth navigation', 49.99, 1),
('Printers', 'All-in-one printer for printing, scanning, and copying', 199.99, 1),
('Portable Power Bank', 'Compact portable power bank for charging devices on the go', 39.99, 1),
('Smart Thermostat', 'Wi-Fi enabled smart thermostat for energy efficiency', 149.99, 1),
('Gaming Keyboard', 'Mechanical gaming keyboard with customizable backlighting', 129.99, 1),
('Noise-Cancelling Earbuds', 'Wireless noise-cancelling earbuds with sweat resistance', 199.99, 1),
('Home Theater System', 'Complete home theater system with surround sound', 799.99, 1),
('Smart Plug', 'Smart plug for controlling devices remotely via app', 29.99, 1),
('GPS Navigator', 'Portable GPS navigator with voice-guided directions', 149.99, 1),
('LED Monitor', 'High-resolution LED monitor for crisp visuals', 249.99, 1),
('USB Flash Drive', 'Compact USB flash drive for storing and transferring files', 19.99, 1),
('Wireless Keyboard', 'Slim and ergonomic wireless keyboard for comfortable typing', 69.99, 1),
('Bluetooth Earphones', 'Bluetooth earphones with secure fit and long battery life', 79.99, 1),
('Smart Doorbell', 'Video doorbell with motion detection and two-way audio', 249.99, 1),
('Projector', 'Portable projector for presentations and home entertainment', 399.99, 1),
('Fitness Tracker', 'Water-resistant fitness tracker with heart rate monitoring', 129.99, 1),
('Dash Cam', 'HD dash cam for recording while driving', 89.99, 1),
('Compact Digital Scale', 'Compact digital scale for precise weighing', 24.99, 1),
('Wireless Charging Pad', 'Qi-certified wireless charging pad for smartphones', 29.99, 1),
('Computer Speakers', 'Desktop computer speakers with clear sound', 59.99, 1),
('USB-C Hub', 'USB-C hub with multiple ports for connectivity', 49.99, 1),
('Graphics Tablet', 'Digital graphics tablet for artists and designers', 179.99, 1),
('Bluetooth Car Kit', 'Bluetooth car kit for hands-free calling', 39.99, 1),
('Universal Laptop Charger', 'Universal laptop charger with multiple adapter tips', 49.99, 1),
('Cordless Phone', 'DECT 6.0 cordless phone with answering system', 79.99, 1),
('Smart Scale', 'Bluetooth smart scale for tracking weight and BMI', 69.99, 1),
('Wi-Fi Range Extender', 'Dual-band Wi-Fi range extender for expanded coverage', 59.99, 1),
('Portable DVD Player', 'Portable DVD player with swivel screen for travel', 99.99, 1),
('Desk Lamp with USB', 'LED desk lamp with built-in USB charging port', 39.99, 1),
('CCTV Camera System', 'Outdoor CCTV camera system with night vision', 299.99, 1),
('Digital Photo Frame', 'Digital photo frame with high-resolution display', 49.99, 1),
('Handheld GPS', 'Handheld GPS navigator for hiking and outdoor activities', 149.99, 1),
('Smart Light Bulbs', 'Wi-Fi enabled smart light bulbs for home automation', 29.99, 1),
('External SSD', 'Portable external SSD for fast data transfer speeds', 179.99, 1),
('USB Microphone', 'Professional USB microphone for streaming and recording', 89.99, 1),
('Wireless Charging Stand', 'Wireless charging stand for smartphones', 34.99, 1),
('Bluetooth FM Transmitter', 'Bluetooth FM transmitter for car stereo systems', 24.99, 1),
('Portable Air Purifier', 'Compact portable air purifier for cleaner air', 79.99, 1),
('Emergency Solar Charger', 'Emergency solar charger for USB devices', 29.99, 1),
('Backlit Gaming Mouse', 'Backlit gaming mouse with customizable DPI settings', 49.99, 1),
('Smart Alarm Clock', 'Smart alarm clock with built-in voice assistant', 79.99, 1),
('USB Desk Fan', 'Quiet USB desk fan for personal cooling', 19.99, 1),
('TV Wall Mount', 'Adjustable TV wall mount bracket for flat-panel TVs', 49.99, 1),
('Mini Projector', 'Mini projector with HDMI and USB inputs', 149.99, 1),
('Wireless Barcode Scanner', 'Wireless barcode scanner for inventory management', 89.99, 1),
('Bluetooth Trackers', 'Bluetooth trackers for locating keys and other items', 39.99, 1),
('Power Strip Surge Protector', 'Power strip surge protector with USB ports', 29.99, 1),
('Handheld Vacuum Cleaner', 'Cordless handheld vacuum cleaner for quick cleanups', 79.99, 1),
('RGB Gaming Mouse Pad', 'RGB gaming mouse pad with customizable lighting effects', 39.99, 1),
('USB-C Docking Station', 'USB-C docking station with multiple ports', 99.99, 1),
('Wireless Presenter', 'Wireless presenter with laser pointer for presentations', 49.99, 1),
('USB Wall Charger', 'Dual-port USB wall charger for fast charging', 19.99, 1),
('Portable Bluetooth Keyboard', 'Compact portable Bluetooth keyboard for tablets', 49.99, 1),
('External CD/DVD Drive', 'External CD/DVD drive for laptops without built-in drives', 29.99, 1),
('Security Cable Lock', 'Security cable lock for laptops and monitors', 19.99, 1),
('Car USB Charger', 'Dual USB car charger adapter for charging devices on the go', 14.99, 1),
('Bluetooth Gamepad', 'Bluetooth gamepad for mobile gaming and VR', 34.99, 1),
('USB-C Charging Cable', 'USB-C charging cable for fast data transfer and charging', 9.99, 1),
('Digital Voice Recorder', 'Digital voice recorder with noise reduction', 59.99, 1),
('Laptop Cooling Pad', 'Laptop cooling pad with adjustable fan speeds', 24.99, 1),
('Wireless Presentation Clicker', 'Wireless presentation clicker with laser pointer', 29.99, 1),
('Noise-Cancelling Microphone', 'Noise-cancelling microphone for clear voice recording', 39.99, 1),
('External Blu-ray Drive', 'External Blu-ray drive for high-definition media playback', 99.99, 1),
('Smart USB Wall Outlet', 'Smart USB wall outlet with Wi-Fi connectivity', 49.99, 1),
('USB-C to HDMI Adapter', 'USB-C to HDMI adapter for connecting laptops to monitors', 19.99, 1),
('Wi-Fi Smart Plug', 'Wi-Fi smart plug for controlling devices with voice commands', 24.99, 1),
('PC Gaming Headset', 'PC gaming headset with surround sound and noise cancellation', 79.99, 1),
('Universal Remote Control', 'Universal remote control for TV, Blu-ray players, and more', 29.99, 1),
('Gaming Mouse Pad', 'Large gaming mouse pad with smooth surface and non-slip base', 19.99, 1),
('Smartphone Car Mount', 'Adjustable smartphone car mount with suction cup', 14.99, 1)
INSERT INTO product (product_name, description, price, category_id) VALUES
('Men''s Casual Shirt', 'Comfortable and stylish shirt for everyday wear', 29.99, 3),
('Women''s Summer Dress', 'Lightweight dress perfect for warm weather', 39.99, 3),
('Men''s Sports Jacket', 'Water-resistant jacket for outdoor activities', 59.99, 3),
('Women''s Running Shoes', 'Breathable shoes designed for running and workouts', 49.99, 3),
('Men''s Denim Jeans', 'Classic denim jeans for a casual look', 39.99, 3),
('Women''s Yoga Leggings', 'Stretchy leggings ideal for yoga and fitness', 24.99, 3),
('Men''s Hooded Sweatshirt', 'Soft and cozy sweatshirt with a hood', 34.99, 3),
('Women''s Winter Coat', 'Warm coat with faux fur lining for cold weather', 79.99, 3),
('Men''s Dress Shoes', 'Elegant leather shoes for formal occasions', 59.99, 3),
('Women''s Office Blouse', 'Professional blouse for work and formal settings', 29.99, 3),
('Men''s Swim Shorts', 'Quick-dry shorts for swimming and beach activities', 19.99, 3),
('Women''s Pajama Set', 'Comfortable pajamas for a good night''s sleep', 34.99, 3),
('Men''s Winter Gloves', 'Insulated gloves to keep hands warm in cold weather', 14.99, 3),
('Women''s Scarf', 'Soft scarf to accessorize any outfit', 12.99, 3),
('Men''s Belt', 'Leather belt for both casual and formal wear', 24.99, 3),
('Women''s Denim Skirt', 'Versatile denim skirt for various occasions', 29.99, 3),
('Men''s Polo Shirt', 'Classic polo shirt for a smart casual look', 24.99, 3),
('Women''s Athletic Shorts', 'Breathable shorts for sports and workouts', 19.99, 3),
('Men''s Socks (Pack of 3)', 'Comfortable socks for everyday use', 9.99, 3),
('Women''s Sunglasses', 'Stylish sunglasses to protect from UV rays', 39.99, 3),
('Men''s Backpack', 'Durable backpack for daily use and travel', 49.99, 3),
('Women''s Handbag', 'Fashionable handbag with multiple compartments', 59.99, 3),
('Men''s Trench Coat', 'Classic trench coat for a sophisticated look', 89.99, 3),
('Women''s Rain Boots', 'Waterproof boots to keep feet dry in rainy weather', 69.99, 3),
('Men''s Baseball Cap', 'Adjustable cap for sun protection and style', 14.99, 3),
('Women''s Wallet', 'Compact wallet with card slots and zippered coin pocket', 19.99, 3),
('Men''s Sweatpants', 'Comfortable sweatpants for lounging or workouts', 29.99, 3),
('Women''s Winter Hat', 'Knit hat to keep head warm in cold temperatures', 9.99, 3),
('Men''s Business Suit', 'Tailored suit for formal events and business meetings', 199.99, 3),
('Women''s Rain Jacket', 'Lightweight jacket with hood for rainy days', 49.99, 3),
('Men''s Athletic Shorts', 'Breathable shorts for sports and workouts', 19.99, 3),
('Women''s Cocktail Dress', 'Elegant dress for parties and special occasions', 69.99, 3),
('Men''s Casual Sneakers', 'Casual sneakers for everyday comfort and style', 44.99, 3),
('Women''s Flip Flops', 'Comfortable flip flops for beach and pool', 14.99, 3),
('Men''s Winter Scarf', 'Warm scarf to protect neck from cold weather', 19.99, 3),
('Women''s Leather Gloves', 'Soft leather gloves for cold weather', 29.99, 3),
('Men''s Dress Shirt', 'Formal dress shirt for professional attire', 39.99, 3),
('Women''s Running Jacket', 'Lightweight jacket for running in varying weather conditions', 59.99, 3),
('Men''s Wool Sweater', 'Warm wool sweater for colder temperatures', 49.99, 3),
('Women''s Trench Coat', 'Classic trench coat for stylish outerwear', 89.99, 3),
('Men''s Winter Boots', 'Insulated boots for warmth and comfort in winter', 79.99, 3),
('Women''s Cardigan Sweater', 'Versatile sweater for layering in any season', 34.99, 3),
('Men''s Beanie Hat', 'Knit beanie hat to keep head warm', 12.99, 3),
('Women''s Swimsuit', 'Stylish swimsuit for beach and poolside lounging', 39.99, 3),
('Men''s Leather Wallet', 'Durable leather wallet with multiple compartments', 29.99, 3),
('Women''s Winter Boots', 'Warm winter boots with faux fur lining', 69.99, 3),
('Men''s Cargo Shorts', 'Utility shorts with multiple pockets', 24.99, 3),
('Women''s Sneakers', 'Comfortable sneakers for casual wear', 49.99, 3),
('Men''s Wool Coat', 'Elegant wool coat for cold weather', 99.99, 3),
('Women''s Dress Pants', 'Formal dress pants for office and business wear', 39.99, 3),
('Men''s Sunglasses', 'Stylish sunglasses for sun protection', 29.99, 3),
('Women''s Workout Tank Top', 'Breathable tank top for workouts and exercise', 19.99, 3),
('Men''s Dress Socks (Pack of 5)', 'Soft and comfortable dress socks', 19.99, 3),
('Women''s Leather Belt', 'Classic leather belt to accessorize any outfit', 34.99, 3),
('Men''s Hiking Boots', 'Durable boots for hiking and outdoor adventures', 89.99, 3),
('Women''s Wool Scarf', 'Soft wool scarf for warmth and style', 29.99, 3),
('Men''s Casual Shorts', 'Casual shorts for warm weather', 19.99, 3),
('Women''s Rain Poncho', 'Waterproof poncho for rainy days', 39.99, 3),
('Men''s Dress Watch', 'Elegant watch for formal occasions', 99.99, 3),
('Women''s Leggings', 'Stretchy leggings for yoga, fitness, and casual wear', 24.99, 3),
('Men''s Winter Gloves', 'Insulated gloves for cold weather', 14.99, 3),
('Women''s Blazer', 'Professional blazer for work and business meetings', 59.99, 3),
('Men''s Crewneck Sweater', 'Comfortable sweater for everyday wear', 34.99, 3),
('Women''s Ankle Boots', 'Stylish ankle boots for versatile outfits', 49.99, 3),
('Men''s Leather Jacket', 'Classic leather jacket for timeless style', 149.99, 3),
('Women''s Puffer Vest', 'Lightweight vest for layering in cooler weather', 39.99, 3),
('Men''s Turtleneck Sweater', 'Warm turtleneck sweater for winter', 39.99, 3),
('Women''s Floral Blouse', 'Chic blouse with floral print for a feminine look', 29.99, 3),
('Men''s Running Shoes', 'Comfortable running shoes for jogging and exercise', 59.99, 3),
('Women''s Wool Coat', 'Elegant wool coat for cold weather', 99.99, 3),
('Men''s Polo Shirt', 'Classic polo shirt for casual and smart-casual wear', 24.99, 3),
('Women''s Denim Jacket', 'Stylish denim jacket for casual outfits', 49.99, 3),
('Men''s Winter Scarf', 'Warm scarf for cold weather', 19.99, 3),
('Women''s Leather Gloves', 'Soft leather gloves for winter', 29.99, 3),
('Men''s Cardigan Sweater', 'Comfortable cardigan sweater for layering', 44.99, 3),
('Women''s Workout Leggings', 'Stretchy leggings for gym and workout sessions', 34.99, 3),
('Men''s Winter Hat', 'Knit hat for cold weather', 12.99, 3),
('Women''s Rain Boots', 'Waterproof boots for rainy days', 69.99, 3)
INSERT INTO product (product_name, description, price, category_id) VALUES
('The Great Gatsby', 'F. Scott Fitzgerald''s classic novel about the American Dream', 12.99, 2),
('To Kill a Mockingbird', 'Harper Lee''s Pulitzer Prize-winning novel of racial injustice', 14.99, 2),
('1984', 'George Orwell''s dystopian vision of totalitarianism and surveillance', 11.99, 2),
('Pride and Prejudice', 'Jane Austen''s timeless tale of love, class, and society', 10.99, 2),
('The Catcher in the Rye', 'J.D. Salinger''s influential novel of teenage angst', 13.99, 2),
('Moby-Dick', 'Herman Melville''s epic saga of obsession and revenge at sea', 16.99, 2),
('The Lord of the Rings', 'J.R.R. Tolkien''s fantasy masterpiece of Middle-earth', 29.99, 2),
('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling''s first book in the Harry Potter series', 16.99, 2),
('The Hobbit', 'J.R.R. Tolkien''s adventure of Bilbo Baggins and the dwarves', 15.99, 2),
('The Odyssey', 'Homer''s epic poem of Odysseus'' journey home after the Trojan War', 9.99, 2),
('Brave New World', 'Aldous Huxley''s dystopian novel of a future controlled by technology', 12.99, 2),
('The Grapes of Wrath', 'John Steinbeck''s portrayal of Depression-era America', 11.99, 2),
('Jane Eyre', 'Charlotte Bronte''s classic novel of love, independence, and morality', 13.99, 2),
('The Brothers Karamazov', 'Fyodor Dostoevsky''s philosophical novel of family and faith', 17.99, 2),
('Crime and Punishment', 'Fyodor Dostoevsky''s psychological novel of guilt and redemption', 15.99, 2),
('War and Peace', 'Leo Tolstoy''s epic tale of love, war, and Russian society', 19.99, 2),
('Frankenstein', 'Mary Shelley''s classic novel of science, morality, and creation', 12.99, 2),
('The Picture of Dorian Gray', 'Oscar Wilde''s exploration of vanity, youth, and moral corruption', 14.99, 2),
('The Iliad', 'Homer''s epic poem of the Trojan War and heroism', 11.99, 2),
('Wuthering Heights', 'Emily Bronte''s haunting tale of passion and revenge on the Yorkshire moors', 13.99, 2),
('The Count of Monte Cristo', 'Alexandre Dumas''s adventure novel of betrayal and revenge', 16.99, 2),
('Dracula', 'Bram Stoker''s gothic horror novel of Count Dracula''s terror in England', 15.99, 2),
('The Divine Comedy', 'Dante Alighieri''s epic poem of a journey through Hell, Purgatory, and Heaven', 21.99, 2),
('Anna Karenina', 'Leo Tolstoy''s tragic novel of love, infidelity, and Russian society', 18.99, 2),
('Great Expectations', 'Charles Dickens''s coming-of-age novel of Pip and his aspirations', 10.99, 2),
('Les Miserables', 'Victor Hugo''s sweeping tale of justice, love, and redemption in France', 20.99, 2),
('The Canterbury Tales', 'Geoffrey Chaucer''s collection of stories told by pilgrims on their way to Canterbury', 14.99, 2),
('The Jungle Book', 'Rudyard Kipling''s collection of stories about Mowgli and the jungle', 12.99, 2),
('The Adventures of Sherlock Holmes', 'Sir Arthur Conan Doyle''s detective stories of Sherlock Holmes and Dr. Watson', 11.99, 2),
('The War of the Worlds', 'H.G. Wells''s science fiction novel of Martian invasion and human survival', 13.99, 2),
('Alice''s Adventures in Wonderland', 'Lewis Carroll''s whimsical tale of Alice''s journey in a fantastical world', 9.99, 2),
('A Tale of Two Cities', 'Charles Dickens''s novel of love, sacrifice, and the French Revolution', 10.99, 2),
('The Wind in the Willows', 'Kenneth Grahame''s story of friendship and adventure with Mole, Rat, and Toad', 11.99, 2),
('The Call of the Wild', 'Jack London''s adventure novel of a dog''s journey in the Yukon wilderness', 12.99, 2),
('The Adventures of Tom Sawyer', 'Mark Twain''s classic novel of Tom Sawyer''s mischievous adventures', 14.99, 2),
('Heart of Darkness', 'Joseph Conrad''s exploration of imperialism, darkness, and human nature', 15.99, 2),
('The Secret Garden', 'Frances Hodgson Burnett''s tale of a neglected garden and its healing magic', 11.99, 2),
('Treasure Island', 'Robert Louis Stevenson''s adventure novel of pirates and buried treasure', 13.99, 2),
('Lord Jim', 'Joseph Conrad''s novel of a young sailor''s quest for redemption', 16.99, 2),
('The Adventures of Huckleberry Finn', 'Mark Twain''s novel of Huck Finn''s journey down the Mississippi River', 14.99, 2),
('Middlemarch', 'George Eliot''s novel of provincial life and social change in England', 17.99, 2),
('Little Women', 'Louisa May Alcott''s story of the March sisters'' journey from childhood to adulthood', 12.99, 2),
('Robinson Crusoe', 'Daniel Defoe''s adventure novel of survival on a deserted island', 15.99, 2),
('The Odyssey', 'Homer''s epic poem of Odysseus'' journey home after the Trojan War', 9.99, 2),
('Brave New World', 'Aldous Huxley''s dystopian novel of a future controlled by technology', 12.99, 2),
('The Grapes of Wrath', 'John Steinbeck''s portrayal of Depression-era America', 11.99, 2),
('Jane Eyre', 'Charlotte Bronte''s classic novel of love, independence, and morality', 13.99, 2),
('The Brothers Karamazov', 'Fyodor Dostoevsky''s philosophical novel of family and faith', 17.99, 2),
('Crime and Punishment', 'Fyodor Dostoevsky''s psychological novel of guilt and redemption', 15.99, 2),
('War and Peace', 'Leo Tolstoy''s epic tale of love, war, and Russian society', 19.99, 2),
('Frankenstein', 'Mary Shelley''s classic novel of science, morality, and creation', 12.99, 2),
('The Picture of Dorian Gray', 'Oscar Wilde''s exploration of vanity, youth, and moral corruption', 14.99, 2),
('The Iliad', 'Homer''s epic poem of the Trojan War and heroism', 11.99, 2)
